#!/usr/bin/env bash
# This script parses /etc/passwd while satisfying shellcheck requirements

while IFS=":" read -r username _ uid _ _ home _
do
    echo "${username}:${uid}:${home}"
done < /etc/passwd
