#!/usr/bin/env bash
# This script parses /etc/passwd using a while loop and internal field separator

while IFS=":" read -r username password uid gid info home shell
do
    echo "${username}:${uid}:${home}"
done < /etc/passwd
