#!/usr/bin/env bash
# This script groups log visitors by IP and HTTP status code from a provided log file

log_file="${1:-apache-access.log}"
awk '{print $1, $9}' "$log_file" | sort | uniq -c | sort -nr
